POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/1559d823-308c-43ad-af2b-8539d1a04f60
Content-Type: application/json

{
    "title": "Video 02",
    "description": "Esse é um novo video",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/1559d823-308c-43ad-af2b-8539d1a04f60